import type { Metadata } from "next";
import { Geist, Geist_Mono,Cormorant_Garamond, Bona_Nova_SC, EB_Garamond   } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css"
import 'aos/dist/aos.css'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300","400","500","600","700"],
  variable: "--font-cormorant",
});

const safiraMarch = localFont({
  src: "./fonts/Safira March Personal Use Only.ttf",
  variable: "--font-safira",
  display: "swap",
})

const bonaNova = Bona_Nova_SC({
  subsets: ["latin"],
  weight: ["400","700"],
  variable: "--font-bona",
  display: "swap",
});

const ebGaramond = EB_Garamond({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-eb-garamond",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cormorant.variable} ${safiraMarch.variable} ${bonaNova.variable} ${ebGaramond.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
